name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    timeout-minutes: 10

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout lndocs
        uses: actions/checkout@v3
        with:
          repository: laminlabs/lndocs
          ssh-key: ${{ secrets.READ_LNDOCS }}
          path: lndocs
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-all
        with:
          path: |
            .nox
            ~/.cache/pre-commit
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('pyproject.yaml') }}
      - name: Install pip and nox
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Lint
        run: |
          nox -s lint
      - name: Build
        run: |
          nox -s build --python ${{ matrix.python-version }}
      - name: Codecov
        if: matrix.python-version == '3.9'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Read lamin-project.yaml
        if: matrix.python-version == '3.9'
        id: lamin-project
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: lamin-project.yaml
          project_slug: project_slug
      - name: Change base URL to project-slug
        if: github.event_name == 'push' && matrix.python-version == '3.9'
        run: |
          mv _build/html _build/html_tmp
          mkdir _build/html
          mv _build/html_tmp _build/html/reports
      - name: Deploy site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --build --dir=_build/html
